// Sample rows for the /design review tile.
//
// Shapes mirror real production rows: very long society conference titles,
// non-GBP currencies, an online webinar, a multi-day congress, a sold-out
// course, an abstract deadline inside the urgency window, and a row with no
// price scraped. Dates are computed relative to today so the tile never goes
// stale and the urgency bands always demonstrate themselves.

import type { DirectoryEvent } from '@/lib/directory'

function inDays(n: number): string {
  const d = new Date()
  d.setHours(12, 0, 0, 0)
  d.setDate(d.getDate() + n)
  return d.toISOString().slice(0, 10)
}

export const SAMPLE_EVENTS: DirectoryEvent[] = [
  {
    id: 1,
    name: 'Delusions, dopaminergic medications, GLP-1 drugs, and eating disorders — South West Autumn Conference',
    href: '#',
    specialty: 'Psychiatry',
    eventType: 'conference',
    isFlagship: false,
    isOnDemand: false,
    isSoldOut: false,
    startDate: inDays(44),
    endDate: null,
    format: 'in_person',
    city: 'Bristol',
    region: 'South West',
    society: 'RCPsych',
    priceMin: 28,
    priceMax: 208,
    currency: 'GBP',
    cpdAccredited: true,
    cpdPoints: 5,
    abstractDeadline: inDays(6),
    abstractDeadlineNote: null,
    abstractOpen: true,
  },
  {
    id: 2,
    name: 'ASCO Annual Meeting 2027 — Advancing Equitable Cancer Care',
    href: '#',
    specialty: 'Oncology',
    eventType: 'conference',
    isFlagship: true,
    isOnDemand: false,
    isSoldOut: false,
    startDate: inDays(212),
    endDate: inDays(215),
    format: 'hybrid',
    city: 'Chicago',
    region: 'Illinois',
    society: 'ASCO',
    priceMin: 795,
    priceMax: 1450,
    currency: 'USD',
    cpdAccredited: true,
    cpdPoints: null,
    abstractDeadline: inDays(96),
    abstractDeadlineNote: null,
    abstractOpen: true,
  },
  {
    id: 3,
    name: 'Basic Surgical Skills — two-day intensive',
    href: '#',
    specialty: 'General Surgery',
    eventType: 'course',
    isFlagship: false,
    isOnDemand: false,
    isSoldOut: true,
    startDate: inDays(19),
    endDate: inDays(20),
    format: 'in_person',
    city: 'London',
    region: 'London',
    society: 'RCSEng',
    priceMin: 720,
    priceMax: 720,
    currency: 'GBP',
    cpdAccredited: true,
    cpdPoints: 12,
    abstractDeadline: null,
    abstractDeadlineNote: null,
    abstractOpen: false,
  },
  {
    id: 4,
    name: 'Recognising sepsis in the deteriorating child: an evening webinar',
    href: '#',
    specialty: 'Paediatrics',
    eventType: 'workshop',
    isFlagship: false,
    isOnDemand: false,
    isSoldOut: false,
    startDate: inDays(9),
    endDate: null,
    format: 'online',
    city: null,
    region: null,
    society: 'RCPCH',
    priceMin: 0,
    priceMax: null,
    currency: 'GBP',
    cpdAccredited: true,
    cpdPoints: 1,
    abstractDeadline: null,
    abstractDeadlineNote: null,
    abstractOpen: false,
  },
  {
    id: 5,
    name: 'ESMO Congress 2027',
    href: '#',
    specialty: 'Medical Oncology',
    eventType: 'conference',
    isFlagship: true,
    isOnDemand: false,
    isSoldOut: false,
    startDate: inDays(378),
    endDate: inDays(382),
    format: 'in_person',
    city: 'Madrid',
    region: 'Spain',
    society: 'ESMO',
    priceMin: 640,
    priceMax: 1180,
    currency: 'EUR',
    cpdAccredited: true,
    cpdPoints: 32,
    abstractDeadline: inDays(2),
    abstractDeadlineNote: null,
    abstractOpen: true,
  },
  {
    id: 6,
    name: 'Emergency Medicine Educators Day',
    href: '#',
    specialty: 'Emergency Medicine',
    eventType: 'conference',
    isFlagship: false,
    isOnDemand: false,
    isSoldOut: false,
    startDate: inDays(36),
    endDate: null,
    format: 'online',
    city: null,
    region: null,
    society: 'RCEM',
    priceMin: 185,
    priceMax: 555,
    currency: 'GBP',
    cpdAccredited: true,
    cpdPoints: 5,
    abstractDeadline: null,
    abstractDeadlineNote: 'see event page for details',
    abstractOpen: true,
  },
  {
    id: 7,
    name: 'Catch-up: Winter pressures and acute medical take — recorded sessions',
    href: '#',
    specialty: 'Acute Internal Medicine',
    eventType: 'conference',
    isFlagship: false,
    isOnDemand: true,
    isSoldOut: false,
    startDate: inDays(12),
    endDate: null,
    format: 'online',
    city: null,
    region: null,
    society: 'RCP',
    priceMin: 45,
    priceMax: 45,
    currency: 'GBP',
    cpdAccredited: false,
    cpdPoints: null,
    abstractDeadline: null,
    abstractDeadlineNote: null,
    abstractOpen: false,
  },
  {
    id: 8,
    name: 'Obstetric anaesthesia: simulation and human factors masterclass',
    href: '#',
    specialty: 'Anaesthetics',
    eventType: 'workshop',
    isFlagship: false,
    isOnDemand: false,
    isSoldOut: false,
    startDate: inDays(-2 + 90),
    endDate: null,
    format: 'in_person',
    city: 'Manchester',
    region: 'North West',
    society: 'RCoA',
    priceMin: null,
    priceMax: null,
    currency: 'GBP',
    cpdAccredited: false,
    cpdPoints: null,
    abstractDeadline: null,
    abstractDeadlineNote: null,
    abstractOpen: false,
  },
]
